[package]
name = "chip16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.1"
byteorder = "1.4.3"
clap = { version = "4.2.7", features = ["derive"] }
rand = "0.8.5"
sdl2 = "0.35.2"
